### ISSUE TITLE
Realizar Simulación Montecarlo para un conjunto seleccionado de PBI

### ISSUE THREAD

**Issue by javimarsal** [javimarsal/flow-estimates-app#14]
El conjunto se selecciona manualmente o por etiqueta

**Comment by paberlo** [comment]
El conjunto de PBI que se seleccione indicando los de un Panel o Release concretos, es mucho lío y poco útil elegir a mano pbi sueltos (es mi opinión, lo discutiremos).

Este PBI tiene que dar respuesta a la pregunta "Cuántos días llevará completar los PBI seleccionados":
1. Calcular throughput histórico entre las fechas seleccionadas. El throughput será el número de PBI finalizados en cada día del rango de fechas.
2. 
lista_dias =[]
**repetir** 5000 (configurable) veces:
   pendientes = nº PBI seleccionados.
   dias = 0
   **repetir** hasta que pendientes = 0:
        n = aleatorio(histórico de throughput diario)
       pendientes = pendientes - n
       dias++
   **fin**
   lista_dias.append(dias)
**fin**
crear histograma con lista_dias
