### ISSUE TITLE
Ver el gráfico de dispersión del producto (con 3 percentiles)

### ISSUE THREAD

**Issue by javimarsal** [javimarsal/flow-estimates-app#4]
Ver detalles de creación de gráfico en el libro "When will it be done"

**Comment by paberlo** [comment]
- cycle time =  done date - start date  + 1
 - Dibujar scatter plot ( date vs cycle time) con todos los items done
-  percentiles 50,85 y 95
- Permitir indicar rango de fechas, para así que los percentiles indiquen al pasado más reciente.
- Una frase sobre la probabilidad (50,85,95) de realizar un nuevo item como mucho en el tiempo indicado por dicho percentil.
 - Indicar con otro color el Item Age de los que no están done pero ya han entrado en el proceso (doing). Item age = current date - start date +1
