### ISSUE TITLE
Al marcar un PBI dentro del gráfico, ver el tiempo máximo del desarrollo según cada percentil

### ISSUE THREAD

**Issue by javimarsal** [javimarsal/flow-estimates-app#5]

**Comment by paberlo** [comment]
este no tiene sentido, se puede borrar.

**Comment by paberlo** [comment]
Esto está mal pensado. No es necesario, pues los percentiles valen para cualquier nuevo PBI. Y de los que están en progreso, solo interesa ver su posición respecto a los percentiles, que ya se ve.
